on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            latexmk -xelatex unicode-math.ltx
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: unicode-math.pdf
          path: unicode-math-doc
